[project]
name = "bless-anime-game"
version = "1.0.0"
description = "3D anime-style action game with AI-powered mechanics"
author = "MyDemir"
timestamp = "2025-05-17 23:15:00"

[build]
entry = "src/core/main.ts"
outDir = "dist"
command = "npm run build:debug"
debug = "tsconfig.debug.json"

[build_release]
entry = "src/core/main.ts"
outDir = "dist"
command = "npm run build:release"
release = "tsconfig.release.json"

[game]
engineVersion = "1.0.0"
renderEngine = "three.js"
aiSystem = true

[server]
port = 3000
host = "localhost"

[paths]
public = "public"
source = "src"
assets = "public/models"

[deployment]
permission = "public"
nodes = 1
