[project]
name = "bless-anime-game"
version = "1.0.0"
description = "3D anime-style action game with AI-powered mechanics"
author = "MyDemir"
timestamp = "2025-05-17 23:15:00"

[build]
dir = "build"
command = "npm run build:debug"
debug = "tsconfig.debug.json"
module_type = "esm"

[build_release]
dir = "build"
command = "npm run build:release"
release = "tsconfig.release.json"
module_type = "esm"

[game]
engineVersion = "1.0.0"
renderEngine = "three.js"

[server]
port = 3_000
host = "localhost"
mime_types = { "js" = "application/javascript", "mjs" = "application/javascript" }
cors_enabled = true

[paths]
public = "public"
source = "src"
assets = "public/models"
data = "public/data"

[deployment]
permission = "public"
nodes = 3
serve_static = true
content_type = true

[static]
directory = "public"
index = "index.html"
mime_types = { "js" = "application/javascript", "mjs" = "application/javascript" }
