[project]
name = "bless-anime-game"
version = "1.0.0"
description = "3D anime-style action game with AI-powered mechanics"
author = "MyDemir"
timestamp = "2025-05-17 23:15:00"

[build]
entry = "index.ts"  # esbuild için TS giriş noktası
dir = "build"       # esbuild çıktıları için yeni dizin
outDir = "build"
command = "esbuild index.ts --bundle --outfile=build/debug.js --format=iife --platform=browser"  # esbuild debug komutu
wasm = "build/debug.wasm"  # WASM çıktısı (esbuild sonrası ek işlemle üretiliyorsa)

[build_release]
entry = "index.ts"  # esbuild için TS giriş noktası
dir = "build"       # esbuild çıktıları için yeni dizin
outDir = "build"
command = "esbuild index.ts --bundle --minify --outfile=build/bless-anime-game.js --format=iife --platform=browser"  # esbuild release komutu
wasm = "build/bless-anime-game.wasm"  # WASM çıktısı

[game]
engineVersion = "1.0.0"
renderEngine = "three.js"
aiSystem = true

[server]
port = 3000
host = "localhost"

[paths]
public = "public"
source = "src"
assets = "public/models"

[deployment]
permission = "public"
nodes = 1

[preview]
wasm = "build/debug.wasm"  # Önizleme için güncellenmiş WASM yolu
