[project]
name = "bless-anime-game"
version = "1.0.0"
description = "3D anime-style action game with AI-powered mechanics"
author = "MyDemir"
timestamp = "2025-05-17 23:15:00"

[build]
# Bu komut, package.json'daki "build:debug" script'ini çağıracak.
# Bu script, hem tarayıcı JS'ini hem de Blockless WASM'i üretecek.
command = "npm run build:debug"
dir = "build"
# Buradaki "entry" alanı, 'command' ile üretilen WASM dosyasının adını belirtir.
entry = "debug.wasm"

[build_release]
# Bu komut, package.json'daki "build:release" script'ini çağıracak.
command = "npm run build:release"
dir = "build"
# Buradaki "entry" alanı, 'command' ile üretilen WASM dosyasının adını belirtir.
entry = "bless-anime-game.wasm"

[game]
engineVersion = "1.0.0"
renderEngine = "three.js"
aiSystem = true

[server]
port = 3000
host = "localhost"

[paths]
public = "public"
source = "src"
assets = "public/models"

[deployment]
permission = "public"
nodes = 1

[preview]
# `bls preview` komutu bu WASM dosyasını kullanacak.
wasm = "build/debug.wasm"
