[project]
name = "bless-anime-game"
version = "1.0.0"
description = "3D anime-style action game with AI-powered mechanics"
author = "MyDemir"
timestamp = "2025-05-17 23:15:00"

[build]
entry = "src/core/main.ts"  # index.ts yerine tam yol
dir = "build"              # fix/path-run önerisi, package.json ile uyumlu
outDir = "build"
command = "npm run build:debug"
debug = "tsconfig.debug.json"
wasm = "build/debug.wasm"

[build_release]
entry = "src/core/main.ts"
dir = "build"
outDir = "build"
command = "npm run build:release"
release = "tsconfig.release.json"
wasm = "build/bless-anime-game.wasm"

[game]
engineVersion = "1.0.0"
renderEngine = "three.js"
aiSystem = true

[server]
port = 3000
host = "localhost"

[paths]
public = "public"
source = "src"
assets = "public/models"

[deployment]
permission = "public"
nodes = 1

[preview]
wasm = "build/debug.wasm"
