[project]
name = "bless-anime-game"
version = "1.0.0"
description = "3D anime-style action game with AI-powered mechanics"
author = "MyDemir"
timestamp = "2025-05-17 23:15:00"

[build]
dir = "build"
entry = "debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "release.wasm" # öneri denemesi 
command = "npm run build:release"

[game]
engineVersion = "1.0.0"
renderEngine = "three.js"
aiSystem = true

[server]
port = 3000
host = "localhost"

[paths]
public = "public"
source = "src"
assets = "public/models"

[deployment]
permission = "public"
nodes = 1

[preview]
wasm = "build/debug.wasm"
