[project]
name = "bless-anime-game"
version = "1.0.0"
description = "3D anime-style action game with AI-powered mechanics"
author = "MyDemir"
timestamp = "2025-05-17 23:15:00"

[build]
# Bu komut, package.json'daki "build:debug" script'ini çağıracak.
# Bu script, hem JS hem de WASM dosyalarını üretecektir.
command = "npm run build:debug"
dir = "build"
entry = "debug.wasm" # package.json'daki bls-sdk-ts komutunun -f bayrağıyla aynı olmalı

[build_release]
# Bu komut, package.json'daki "build:release" script'ini çağıracak.
command = "npm run build:release"
dir = "build"
entry = "bless-anime-game.wasm" # package.json'daki bls-sdk-ts komutunun -f bayrağıyla aynı olmalı

[game]
engineVersion = "1.0.0"
renderEngine = "three.js"
aiSystem = true

[server]
port = 3000
host = "localhost"

[paths]
public = "public"
source = "src"
assets = "public/models"

[deployment]
permission = "public"
nodes = 1

[preview]
# `blessnet preview` komutu doğrudan bu WASM dosyasını kullanacak.
wasm = "build/debug.wasm"
