[project]
name = "bless-anime-game"
version = "1.0.0"
description = "3D anime-style action game with AI-powered mechanics"
author = "MyDemir"
timestamp = "2025-05-16 19:29:23"

[build]
entry = "src/index.ts"
outDir = "dist"
debug = "tsconfig.debug.json"
release = "tsconfig.release.json"

[game]
engineVersion = "1.0.0"
renderEngine = "three.js"
aiSystem = true

[dependencies]
three = "^0.150.0"
typescript = "^4.9.0"
vite = "^4.0.0"
