[project]
name = "bless-anime-game"
version = "1.0.0"
description = "3D anime-style action game with AI-powered mechanics"
author = "MyDemir"
timestamp = "2025-05-17 23:15:00"

[build]
entry = "index.ts"
dir = "build"
outDir = "build"
command = "esbuild src/core/main.ts --bundle --outfile=build/index.js --format=iife --platform=browser --sourcemap"
wasm = "build/debug.wasm"

[build_release]
entry = "index.ts"
dir = "build"
outDir = "build"
command = "esbuild src/core/main.ts --bundle --minify --outfile=build/index.js --format=iife --platform=browser --sourcemap"
wasm = "build/bless-anime-game.wasm"

[game]
engineVersion = "1.0.0"
renderEngine = "three.js"
aiSystem = true

[server]
port = 3000
host = "localhost"

[paths]
public = "public"
source = "src"
assets = "public/models"

[deployment]
permission = "public"
nodes = 1

[preview]
wasm = "build/debug.wasm"
